spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console
  jackson:
    default-property-inclusion: non_null

bot:
  name: ${BOT_NAME}
  token: ${BOT_TOKEN}

vk:
  app-id: 8030150
  redirect-uri: ${REDIRECT_URL}
  token-url: "https://oauth.vk.com/authorize"
  waiting-login-time: ${WAITING_LOGIN_TIME}

logging:
  file:
    name: logs/StickerFace.log
  logback:
    rollingpolicy:
      max-file-size: 10KB
      file-name-pattern: logs/StickerFace-%d{yyyy-MM-dd-HH-mm}.%i.log
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss}] [ %-5level] ${PID:- } [%thread] %logger{15} - %msg%n"
    file: "[%d{yyyy-MM-dd HH:mm:ss}] [ %-5level] ${PID:- } [%thread] %logger{15} - %msg%n"
