spring:
  datasource:
    url: jdbc:h2:mem:db;DB_CLOSE_DELAY=-1
    username: username
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
  h2:
    console:
      enabled: true
      path: /h2-console
  jackson:
    default-property-inclusion: non_null

bot:
  name: VkMirroringBot
  token: "1915762352:AAHaW2XeNZJCYuZ9P10LFJk9zKPgFurx2Qg"

vk:
  app-id: 8030150
  redirect-uri: "http://192.168.31.160:8080/login.html"
  token-url: "https://oauth.vk.com/authorize"
  waiting-login-time: 60000

logging:
  file:
    name: logs/StickerFace.log
  logback:
    rollingpolicy:
      max-file-size: 10KB
      file-name-pattern: logs/StickerFace-%d{yyyy-MM-dd-HH-mm}.%i.log
  pattern:
    console: "[%d{yyyy-MM-dd HH:mm:ss}] [ %-5level] ${PID:- } [%thread] %logger{15} - %msg%n"
    file: "[%d{yyyy-MM-dd HH:mm:ss}] [ %-5level] ${PID:- } [%thread] %logger{15} - %msg%n"
